---
- name: Setup
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: update
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: allow ufw
      command: ufw allow 'Nginx HTTP'

    - name: start nginx
      systemd:
        name: nginx
        enabled: yes
        state: started