name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and update files
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          scp -i ssh_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./index.html ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_HOST }} 'sudo mv /home/ubuntu/index.html /var/www/html/index.html'
        shell: bash

