name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2 instance host
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        source: "index.html"  # Only upload index.html
        target: "/var/www/html"  # Target directory on EC2

    - name: Remove default index file
      run: |
        ssh -i ${{ secrets.SSH_KEY }} ubuntu@${{ secrets.EC2_HOST }} "sudo rm /var/www/html/index.nginx-debian.html"
